# Simplified Netdata Docker Compose for AOB Platform

version: '3.8'

services:
  # Main Netdata instance
  netdata:
    image: netdata/netdata:latest
    container_name: netdata-main
    hostname: netdata-main
    ports:
      - "19999:19999"
    volumes:
      - netdata_config:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
      - netdata_log:/var/log/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NETDATA_CLAIM_TOKEN=netdata-claim-token
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=netdata-rooms
      - NETDATA_CLAIM_PROXY=
      - NETDATA_CLAIM_EXTRA=
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19999/api/v1/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  netdata_config:
    driver: local
  netdata_lib:
    driver: local
  netdata_cache:
    driver: local
  netdata_log:
    driver: local
