services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - audit

  agent_registry:
    build:
      context: ..
      dockerfile: docker/Dockerfile.agent_registry
    ports:
      - "8081:8081"

  session_service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.session_service
    ports:
      - "8082:8082"

  metering:
    build:
      context: ..
      dockerfile: docker/Dockerfile.metering_service
    ports:
      - "8083:8083"

  audit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.audit_service
    ports:
      - "8085:8085"

  opa:
    image: openpolicyagent/opa:0.64.1
    command: ["run", "--server", "/policies"]
    volumes:
      - ../policies:/policies:ro
    ports:
      - "8181:8181"

  execution:
    build:
      context: ..
      dockerfile: docker/Dockerfile.execution_service
    ports:
      - "8086:8086"

  model_gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile.model_gateway
    ports:
      - "8087:8087"

  tool_gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile.tool_gateway
    ports:
      - "8088:8088"

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    environment:
      - PYTHONUNBUFFERED=1
      - AOB_POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/aob
      - AOB_KAFKA_BOOTSTRAP=kafka:9092
      - AOB_KAFKA_TOPIC=aob.events
      - AOB_OUTBOX_POLL_SECS=1.0
      - AOB_OUTBOX_BATCH=100
    depends_on:
      - postgres
      - kafka

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=aob
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

