global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AOB API Service
  - job_name: 'aob-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # AOB Worker Service
  - job_name: 'aob-worker'
    static_configs:
      - targets: ['worker:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # AOB Audit Service
  - job_name: 'aob-audit'
    static_configs:
      - targets: ['audit:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # AOB Model Gateway
  - job_name: 'aob-model-gateway'
    static_configs:
      - targets: ['model_gateway:8087']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # AOB Tool Gateway
  - job_name: 'aob-tool-gateway'
    static_configs:
      - targets: ['tool_gateway:8088']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # AOB Tenant Manager
  - job_name: 'aob-tenant-manager'
    static_configs:
      - targets: ['tenant_manager:8089']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Postgres Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  # Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
