
name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install core
        run: |
          pip install -e packages/agentic_core
      - name: Install API (for imports)
        run: |
          pip install -e services/api
      - name: Run tests
        run: |
          pip install pytest pytest-asyncio
          pytest -q
